### ISSUE TITLE
 t-SNE: is this a good use case for t-SNE to compress 1M features down to few k features?

### ISSUE THREAD

**Issue by Tagar** [saurfang/spark-tsne#13]
This project was references in my Data Science question at https://datascience.stackexchange.com/a/35561/5380 

It seems t-SNE is more suited for data visualization tasks? Than for our use case where we still want to keep as much variance as possible for modeling (see above that we're planning to bring down number features to several thousand). 

t-SNE's focus is reducing down to 2-dimensions so it can be visualized? See lvdmaaten.github.io/tsne - 

> **Can I use t-SNE to embed data in more than two dimensions?**
> 
> Well, yes you can, but there is a catch. The key characteristic of t-SNE is that it solves a problem known as the crowding problem. The extent to which this problem occurs depends on the ratio between the intrinsic data dimensionality and the embedding dimensionality. So, if you embed in, say, thirty dimensions, the crowding problem is less severe than when you embed in two dimensions. As a result, it often works better if you increase the degrees of freedom of the t-distribution when embedding into thirty dimensions (or if you try to embed intrinsically very low-dimensional data such as the Swiss roll). More details about this are described in the AI-STATS paper.

Would it be a good use case for t-SNE to create a low-rank matrix of 1M features X 60M rows down to few thousand features? Would saurfang/spark-tsne scale to such datasets? 

Thanks!

**Comment by saurfang** [comment]
Agree. I wouldn't use tsne for feature compression. It is not very runtime efficient comparing to PCA for example and I doubt the current implementation would scale to your dataset. I don't have a recommendation for alternative though.

**Comment by Tagar** [comment]
Thank you @saurfang
